### ISSUE TITLE
Ootd.getImageCount()가 0일 때 오류를 발생하는 문제.

### ISSUE THREAD

**Issue by Lechros** [ootd-zip/server#249]
https://github.com/ootd-zip/server/blob/ccf47c31ec15546ffff5b66debc630830432849f/src/main/java/zip/ootd/ootdzip/ootd/domain/Ootd.java#L217-L222

이미지가 없다면 0을 반환하는 게 올바른 동작으로 보입니다.

---

(이미지가 없는 OOTD가 존재할 수 있나요?)

**Comment by jinhoon227** [comment]
로직상 존재할 수 없지만, 테스트를 위해서 DB 에 직접 때려넣은 데이터가 있을시 문제가 발생해서 추가가 되어있습니다.
