### ISSUE TITLE
BaseEntity의 속성이 제대로 초기화되지 않음

### ISSUE THREAD

**Issue by Lechros** [ootd-zip/server#33]
BaseEntity를 상속받은 항목(User)을 추가하고 MariaDB에 접속하여 확인해 본 결과 CreatedAt과 ModifiedAt의 값이 null로 저장되어 있었음. 제대로 날짜가 저장될 수 있도록 수정하자.

**Comment by kkmin223** [comment]
요거 옷 저장 풀리퀘스트에 수정했었는데, OotdzipApplication에 @EnableJpaAuditing 어노테이션 추가하면 됩니다!
